services:
  db:
    image: postgres:17.11@sha256:67f41722b7a8cbdb868a44a4995c846eddfdc2973bccb291ce937dce88ad5675
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: cs2cup
    ports:
      - '127.0.0.1:55432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d cs2cup']
      interval: 3s
      timeout: 3s
      retries: 20

  rest:
    image: postgrest/postgrest:v16.2@sha256:85258123312dc496ad4c2ed832154a65e9746f84df0d6d09b44229ff9230c08e
    environment:
      PGRST_DB_URI: postgres://anon_authenticator:local-anon-only@db:5432/cs2cup
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMAS: public
    ports:
      - '127.0.0.1:53000:3000'
    depends_on:
      db:
        condition: service_healthy

  rest-admin:
    image: postgrest/postgrest:v16.2@sha256:85258123312dc496ad4c2ed832154a65e9746f84df0d6d09b44229ff9230c08e
    environment:
      PGRST_DB_URI: postgres://admin_authenticator:local-admin-only@db:5432/cs2cup
      PGRST_DB_ANON_ROLE: club_admin
      PGRST_DB_SCHEMAS: public
    ports:
      - '127.0.0.1:53001:3000'
    depends_on:
      db:
        condition: service_healthy
