services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: cs2cup
    ports:
      - '55432:5432'
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d cs2cup']
      interval: 3s
      timeout: 3s
      retries: 20

  rest:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://postgres:dev@db:5432/cs2cup
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_SCHEMAS: public
    ports:
      - '53000:3000'
    depends_on:
      db:
        condition: service_healthy

  rest-admin:
    image: postgrest/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://postgres:dev@db:5432/cs2cup
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_SCHEMAS: public
    ports:
      - '53001:3000'
    depends_on:
      db:
        condition: service_healthy
